### ISSUE TITLE
Duplicate data doubles file size

### ISSUE THREAD

**Issue by JordyvanDortmont** [facebookincubator/FBX2glTF#218]
Thanks for releasing a new version!

Unfortunately, the buffer in the output contains a lot of duplicate data compared to the previous release. Our `buffer.bin` was 23.6 MB and now it's 47.1 MB, almost exactly twice the size.

When applying some form of compression to the buffers, a large part of the superfluous data can be compressed, but the new compressed file size is still quite a bit larger (30%) than the compressed output of the previous release.

**Comment by zellski** [comment]
Ah crap. Hmm. Cannot immediately reproduce. Do you by any chance have a test asset you're at liberty to share? I'll try a few other FBX's I have lying around, meanwhile.

(And clearly I should add file size to my integration test suite.)

**Comment by zellski** [comment]
Oh, actually, I remember now, an issue some time back, that was never resolved, where certain kinds of animation exports triggered file bloat...

**Comment by JordyvanDortmont** [comment]
Sure! [Here's the link to two example files](https://send.firefox.com/download/3eae1019d2bcd0c8/#p1ZVWUA5Z_E58olDwic0cw), one with three animations, and one without animations.

Both seem to trigger the file bloat with the latest release, so I don't think it's necessarily the animations. Although it might be triggered by something related to the possible presence of animations.

| _Buffer sizes_ | With animations  | Without animations |
| -------------| ------------- | ----------- |
| **v0.9.6**    | ~45 MB           |  ~44 MB      |
| **v0.9.5**    | ~18 MB           | ~17 MB       |

While the FBX files were only about 23 MB (with) and about 13 MB (without).

**Comment by JordyvanDortmont** [comment]
I found something quite interesting when I compiled the executables and tried to convert with both the debug and release builds of `v0.9.6`. The debug build produces a buffer similar to that of `v0.9.5` (~17MB), and the release build produces the ~44 MB of `v0.9.6`.

**Comment by zellski** [comment]
Yikes. That’s a confusing but interesting finding. Not immediately clear how that could happen... but I should be able to dig into it today. Thanks for this excellent info.

**Comment by zellski** [comment]
Can't reproduce under Linux no matter what I try. I'll reboot into Windows.

**Comment by zellski** [comment]
Okay, reproduces in Windows.

**Comment by zellski** [comment]
The bloat came from failures in vertex deduplication, specifically in the case (as you suggested) when there were blend shapes present, whether used in animations or not. The reason comes down to the way struct members are initialised, an area of modern C++ I will admit I've only faintly tried to keep track of.

When I started this project, I was very enamoured with where C++ was going in terms of readability, but increasingly I'm tiring of the endless build times, increasing number of moving parts, a thousand ways to do the same thing, the dramatic variance in support and the amount of undefined and semi-undefined behaviour, and so on. It's clearly possible to grasp it all perfectly, but I have to juggle a half-dozen languages and C++ isn't interesting enough for complete mastery.

**Comment by zellski** [comment]
@JordyvanDortmont At your convenience, could you verify my fix? You can grab the bleeding edge build [here](https://ci.appveyor.com/project/Facebook/fbx2gltf/builds/26517816/artifacts)

**Comment by JordyvanDortmont** [comment]
@zellski Thank you for fixing the file bloat!

I verified the fix with a model containing 62 animations and the debug and release builds both produce a file with exactly the same size.

I can understand your sentiments towards C++. C++ requires you to really dive into the language for some level of mastery, whereas other languages are much easier to grasp, and work with.
