### ISSUE TITLE
Scaling of first children under root node

### ISSUE THREAD

**Issue by j-conrad** [facebookincubator/FBX2glTF#29]
I'm attempting to convert an FBX to glTF where I have a head and hands mesh skinned to a simple skeleton. The FBX has both the mesh and the skeleton at a scale of 1,1,1. For clarity, I've made sure that the transforms are frozen before skinning. However, when it gets converted to glTF, a root node gets created and the first children under that parent get automatically scaled down to 0.01-- in this case, both the first bone in my skeleton as well as the mesh itself. I'm not sure if this is expected behavior, but it seems like a bug. That, or perhaps the converter is expecting a special kind of hierarchy that I'm not setting up properly. Here is one of the questionable snippets of the glTF:

```{
            "children": [
                2,
                3
            ],
            "name": "Neck",
            "rotation": [
                0.0,
                0.0,
                0.0,
                1.0
            ],
            "scale": [
                0.00999999977648258,
                0.00999999977648258,
                0.00999999977648258
            ],
            "translation": [
                -2.09076537947193e-18,
                0.0147347003221512,
                0.0
            ]
        },

**Comment by zellski** [comment]
Hey @j-conrad. This usually happens because Maya's system units is centimeters, while glTF specifies meters. If the scaling bugs you, I believe you could switch Maya to work in meters.

As for the hierarchy, FBX just really likes to have a single root node to hang everything off of. It's possible we could skip writing it out to the glTF... I'll poke around.

**Comment by j-conrad** [comment]
That's what I assumed too. But the scaling occurs when I export in meters, cm, or even mm.

**Comment by zellski** [comment]
That's interesting. The relevant snippet of code is this:
```
    // Use meters as the default unit for glTF
    FbxSystemUnit sceneSystemUnit = pScene->GetGlobalSettings().GetSystemUnit();
    if (sceneSystemUnit != FbxSystemUnit::m) {
        FbxSystemUnit::m.ConvertScene(pScene);
    }
```

That sure looks to me like it ought to be right, but maybe Maya doesn't export the unit correctly, or we misunderstood something way back when that part of the code was written. I'll put it on a TODO list to investigate. If it's totally broken we could add a command line option to skip the scaling.

**Comment by j-conrad** [comment]
I'll attach two FBX files exported from Maya 2018 in ASCII. They are identical except for having chosen the option for unit conversion, meters vs. centimeters. I hope that helps.
Just comparing the two files, it appears that the 'meters' version is putting this line on the offending items (neck joint and mesh):
`P: "Lcl Scaling", "Lcl Scaling", "", "A",0.01,0.01,0.01`

For clarity, my Maya Prefs are set to use Meters. But what I think might be happening is that the FBX exporter likes to assume centimeters as the default. So anytime it isn't cm, it does a conversion. If that's true, then it seems arbitrary to have chosen cm as a default, but I suppose the coders had to choose something, just as you've chosen meters.
[AvatarHeadHands.zip](https://github.com/facebookincubator/FBX2glTF/files/1428264/AvatarHeadHands.zip)

**Comment by zellski** [comment]
Interesting. Thanks for going the extra mile. Beyond what you found, the meters version has lines:
```
		P: "UnitScaleFactor", "double", "Number", "",100
		P: "OriginalUnitScaleFactor", "double", "Number", "",1
```
as opposed to
```
		P: "UnitScaleFactor", "double", "Number", "",1
		P: "OriginalUnitScaleFactor", "double", "Number", "",1
```

I agree with your conclusion. Maya uses centimeters internally; changing your preferred units does nothing to change that. Nor does the FBX exporter actually recompute positional values on export. It just slams a 0.01 scale on each Maya root (each top-level child of the FBX "RootNode").

It's still a bit of a mystery exactly what `FbxSystemUnit::m.ConvertScene(pScene)` does. It seems in an ideal world, it'd undo the scaling, and modify all the control points? The documentation kind of suggests that's what it does.

I will keep this issue open until I have time to investigate... I'm buried in the blend shape export functionality at the moment. I appreciate the test files, they will come in useful. I'm rather inept at actually using Maya myself. :-)

**Comment by j-conrad** [comment]
No problem! Please let me know if you need any more things from the Maya side. I'm a designer and artist by trade so I'm the opposite-- the code side is the black box for me.

I really appreciate your efforts to make this work.

**Comment by zellski** [comment]
After some analysis, it looks like the FBX SDK either does not, or does not reliably, or is not able to, report the export unit originally used. I'm going to guess this part of the chain has been messed with so many times that whatever clean intent there was a decade ago has since degenerate to pure second-guessing pragmatism.

It's still not clear to me why the FBX acts as if cm is the natural unit, when (afaict) Maya's internal default is reported as meters.

In that vein, I think it makes sense to do what I originally wanted:

 - Delete sad, trusting, hopeful, but ultimately meaningless code
 - Work out how to detect when UnitScaleFactor != OriginalUnitScaleFactor
 - Multiply the ratio into the the child nodes of RootNode
 - Divide the ratio into every single mesh vertex, blend shape vertex, and skinning transform

Ugh. I really hate layering so much magic on, especially when it's not at all clear that this solution would result in "meters" ending up in the glTF (which is really the one thing I care most about -- glTF is a clean spec, FBX is a compromised one). I'll give it a whirl and see how painful it is.

**Comment by zellski** [comment]
Okay, ignore most of that. It's really much simpler. What's actually happening is:

- As you found, the centimetre version is the one that exports "cleanly".
- If you export in meters, you get the UnitScaleFactor 100 line, and the Lcl Scaling 0.01 adjustments.
- The code snippet I pasted above from my SDK **does** in fact work -- and its effect is exactly the same as if you were always exporting in meters, meaning you always get the scaling no matter what.
- When I disable this conversion snippet, we end up with glTF without the weird scaling.

So I could probably make you happy by adding a --skip-unit-conversion flag, which would just perpetuate to the glTF all the values and transforms, precisely as they are in the FBX. To use this flag you'd want to make a humanoid model 1.70 cm tall rather than 1.70 meters tall, or it'll be the wrong size in whatever system ends up ingesting the file.

But the ultimate conclusion is still the same as in the previous comment: it should be possible to bake the conversion into the geometry data rather than mess with the transforms.

**Comment by zellski** [comment]
Proof of concept successful --

![image](https://user-images.githubusercontent.com/714167/33522672-c3e4d6a0-d7a6-11e7-9dd8-85c56b03e75e.png)

This bakes the 0.01 factor into every vertex position and blend shape position, and I had to take some extra care that the inverse bind matrices of skinned models weren't busted in the process.

It's not clear how I will rewrite this elegantly, but it's promising.

**Comment by zellski** [comment]
@davilovick Curious if you have an opinion on all this.

**Comment by fire** [comment]
Is it possible to clean this be a pull request?

**Comment by zellski** [comment]
Hey @fire; to be honest I'm not sure how much work is left (or even if it's still 100% guaranteed to always be possible). I thought I had worked out all the complications, but then I tested it on a model that ended up a complete jumble, and I punted in irritation. May I ask what it is about the 0.01 scale factors that particularly troubles you? Is it more than an irritation; do they cause harm in your use case?

**Comment by fire** [comment]
Well the problem for me is that when I'm using the fb2gltf library in godot. The model imports fine, but bones are in the wrong position.

I had to manually add a 0.1 xyz scale and -90 deg x rotation. https://sketchfab.com/models/7ece1ee1b602436dbcfb77e4f58ba8e5

[source.zip](https://github.com/facebookincubator/FBX2glTF/files/1594005/source.zip)

![godot windows opt tools 64_2017-12-29_15-01-00](https://user-images.githubusercontent.com/32321/34449098-674508e4-eca9-11e7-9961-9448ba913179.png)

I'm trying to debug where things are broken.

**Comment by robertlong** [comment]
@zellski the 0.01 scale factor is really hurting us in AFrame when we have to attach entities to bones that don't have scale 1, 1, 1.

Could you publish that branch with your work to apply the scale factor to the vertex data? Otherwise I'll get to work on it myself. This is my top priority right now so I can work on fixing this ASAP.

I also found a really good thread on the Autodesk forums talking about this issue with a potential workaround that you may want to take a look at: https://forums.autodesk.com/t5/fbx-forum/convert-system-unit-of-animation-curves/td-p/4237081

**Comment by zellski** [comment]
@robertlong Apologies. This is one of my highest priorities to work on. Unfortunately I've had to give my other day job obligations all my attention, and that remains true for another week or two.

I did locate the puny bits of code I had committed [here](https://github.com/zellski/FBX2glTF/commit/4fbc7a0f8c6015e86305705fa8936fd869072339), but beware that it makes no attempt to be a general solution yet; this was just run against a single model (that uses both skeleton and morph targets) with known unit conversion (0.01). And as you can see, it's pretty ad-hoc. Nevertheless, it works with the majority of models -- I think the remaining issue is the binding pose.

Note also that @davilovick did work recently on a cleaner PR [here](https://github.com/facebookincubator/FBX2glTF/pull/63); I have unfortunately not had time to look into that in detail.

Robert, David, if you want to put together a full-fledged PR between the two of you, I would be so thrilled. It should work on any incoming pre-existing scale factor, and it has to support skinning.

I should be able to make available the test model I had that was still giving me issues. Let me know if you're interested! I suspect David's PR is quite close.

The code in the final posts of that link up there also looks like it does something quite akin to my branch, but as the final line of the post says, it did not yet tackle the bind pose (which is where I ran into trouble and ran out of time.)

**Comment by zellski** [comment]
I've accepted @davilovick's PR (with a tiny tweak of my own), and so far it performs admirably. I will make a release later today or tomorrow.
