### ISSUE TITLE
[bug] Skinning causes this model to be very tiny and move to weird location. mutant_walking.fbx

### ISSUE THREAD

**Issue by chipweinberger** [facebookincubator/FBX2glTF#52]
[mutant_walking.zip](https://github.com/facebookincubator/FBX2glTF/files/1536659/mutant_walking.zip)

Hey Zellski, 

My fbx converter (open sourced on github soon) is having the same above issue as yours with this file. But the windows "FBX Review" program shows the model correctly. I'm curious your thoughts on why.

Chip

**Comment by zellski** [comment]
Hey Chip,

Interestingly we get different results depending on which viewer we use. My main goto renderer is https://gltf-viewer.donmccurdy.com/ which does fine with Pepe, but seems to completely fail on the mutant. I get very little love from http://sandbox.babylonjs.com/, but it looks like maybe it's mostly bounding box / scale issues. Finally, the standalone app https://github.com/pissang/qtek-model-viewer is really neat, and always worth testing against. In this case that viewer does well with both the models (though Pepe is a bit off to the side).

I **think** what we're running into here is an issue that I've talked to @donmccurdy with a bit recently, which is that it's not well-specified in glTF what should happen when there is a transform both on a mesh and on its associated skeleton. In the case of Pepe it seems very clear that the skeleton is visibly translated from the mesh. I'm not sure what's going on with the mutant, but closer eyeballing of the files might help.

That's all I have right now -- I think at this point I'm going to wait and see what the Khronos/glTF folks come up with; Don says it's on their radar and they're going to add language to the spec to clarify if e.g. one transform should be ignored. Meanwhile all I can suggest is that we try to avoid the skeleton root having a transform on it.

When I ran into problems with this, it was because the FBX SDK applies a 0.01 scale to the children of root nodes, which led to mismatches in the bounding box calculations, which in turn made my model appear microscopic and far into the distance. 

Final caveat: this is all just a guess. It could be something entirely different. I have no spare cycles to dig in in detail at the moment, unfortunately, but I'm very curious to hear if you find out anything further.

**Comment by chipweinberger** [comment]
The skin + mesh transform idea is an interesting one that I haven't given much thought. Thanks for making me aware of that. And thanks for the other viewer suggestions. I've been using https://gltf-viewer.donmccurdy.com/ so far.

I've noticed the 0.01 scale too. As for bounding boxes, since the min and maxes are part of the accessor, shouldn't the min and max bounding box only refer to the raw mesh vertex positions? It's unclear to me why a 0.01 node should affect the values we write in the accessor.

I'll hopefully be doing a deeper dive into this issue.

**Comment by donmccurdy** [comment]
> I've noticed the 0.01 scale too. As for bounding boxes, since the min and maxes are part of the accessor, shouldn't the min and max bounding box only refer to the raw mesh vertex positions? It's unclear to me why a 0.01 node should affect the values we write in the accessor.

@chipweinberger I don't believe min/max in the accessor should be affected by this node's scale, no. The bounding boxes in my viewer are computed from ancestors of the skinned mesh. The skeleton is _not_ an ancestor of the mesh, but because skeleton scale is applied to the mesh (see above; this may change — working on disambiguating this in the glTF spec) the viewer bounding box is off by a factor of 100.

**Comment by chipweinberger** [comment]
Thank you for clarifying that. Makes much more sense.

**Comment by meshula** [comment]
I wonder if it is coincidental that the implicit unit in an FBX file is centimeters? (ref - http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_CC93340E_C4A1_49EE_B048_E898F856CFBF_htm) If someone put a 0.01 node in, it almost seems like someone

1. received an FBX file of the mutant and imported it into a DCC with meter units, without specifying that the units in the FBX file were centimeters, or overriding the default with meters.
2. It was 100x too big so they added a node to scale it down
3. re-exported the file with the 100x shrink node

So my guess is that it is most likely an art asset bug?

**Comment by meshula** [comment]
Ah cool, I see you've been quite far down this road already! I like your comment about how code degenerates into ad hoc second-guessed pragmatism. That sounds like every FBX based pipeline I've ever worked in.

**Comment by zellski** [comment]
FWIW, discussion seems to be still going on about exactly how to solve this in the glTF realm. Meanwhile, I think for FBX2glTF we are hoping to largely bypass the issue by figuring out how to pre-multiply the 0.01 (or whatever) into every vertex in every mesh. Tracking that in #29. I'll leave this open until there's some type of satisfactory conclusion.

**Comment by zellski** [comment]
Fixed, closing!
