### ISSUE TITLE
How can i install the build on an Amazon AMI (EC2) Instance

### ISSUE THREAD

**Issue by siddjha1** [facebookincubator/FBX2glTF#65]
Hello,

Could you give me the steps to install this on my Linux Amazon AMI Ec2 instance?

I am getting these errors when i just copied the binaries to /bin

FBX2glTF: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by FBX2glTF)
FBX2glTF: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by FBX2glTF)

**Comment by zellski** [comment]
@siddjha1 I think this means I compiled FBX2glTF with a fairly modern compiler version, and you're running it on a system too old to have the necessary libstdc support. Googling a bit, it looks like 3.4.19 is the most recent that's supported by default on (some?) EC2 AMI machines.

I don't know if I can build against 3.4.19 and get all the features I need from the compiler, but I can give it a shot at some point. Meanwhile, though, you're best off building your own version of this binary, from source. There are some instructions for how to proceed in the project's main README -- let me know how it goes! You will need CMAKE and gcc/g++ packages installed.

**Comment by zellski** [comment]
Reading up a little more -- it looks like I could probably force a build against GCC 4.8.3, which works with GLIBCXX_3.4.19. That would make things work for you for a little longer. However:
- This is an old GCC. It's from 2014-2015 era. It's very possible my code relies on bug-fixes that have been made since then.
- Even if not, I am desperate to use C++14 features the minute they're generally available. At that point there's probably no way the binary will continue to run on such an old operating system.

It's peculiar that EC2 images should come with such ageing support. I guess they're trying to be very stable and careful. Is it possible you can request a more up-to-date AMI?

**Comment by zellski** [comment]
Reopening to look into GCC 4.8.3 support.

**Comment by zellski** [comment]
I banged my head against trying to get my dockcross/linux-x64 cross-compiler to use an older version of the toolchain, but I only ran into complexities. For now, I advise you attempt to build from source on the target machine -- there are instructions in the top-level README.

**Comment by zellski** [comment]
Note that there's some light at the end of the tunnel here: https://github.com/facebookincubator/FBX2glTF/issues/104

**Comment by siddjha1** [comment]
Hey Zellski,

Thanks for your help. I guess i have just decided to change my AMI to a more recent version. Since this and alot many other binaries were becoming a problem for me :)

Will be using the precompiled libraries in my new instance and will see how things go from there.

Thanks for all your help.

Cheers!

**Comment by zellski** [comment]
I admit I'm relieved you're choosing this route. For me it's so much easier to just rely on a modern toolchain. And as you say, I think much of the world is deserting this older one. Let me know how it works out!
