### ISSUE TITLE
Support for common materials

### ISSUE THREAD

**Issue by rck1** [facebookincubator/FBX2glTF#66]
@zellski Thank you for your efforts on this project!  This is a fantastic tool and was badly needed by the community.

When do you think you will have your next release?  Is v1.0 around the corner?  I'm waiting for the PBR material fix (#55) when converting from an FBX with common materials.  I've been using FBX2GLTF --khr_materials_common flag but three.js just abandoned support for this extension with their latest release ([r90](https://github.com/mrdoob/three.js/pull/13169)).  I'm hoping you can properly encode common materials to PBR like Khronos' COLLADA2GLTF converter.

It's difficult for me to compile your source code in my environment so I rely on your precompiled binaries.  I look forward to your next release!

**Comment by zellski** [comment]
Hey @rck1 -- it is indeed high time for a new release!

I think 1.0 will still be some months off, realistically, but that's because there's quite a long list of features that I still consider essential for a first public non-beta release. That said, we should be able to put out several minor releases before then.

`KHR_materials_common` is indeed doomed. The next version will include support for KHR_materials_unlit, but of course that does nothing for Lambert/Phong models, which are the great majority of old content.

As for https://github.com/facebookincubator/FBX2glTF/issues/55, I should be able to have some sort of fix for that in the next patch release. I'm not sure exactly what to do there -- I think I have to revert to a very simple model that's basically just diffuse texture + hard-coded reasonable roughness/metallic values. But I'll experiment some more.

I will take a look at COLLADA2GLTF; I have not kept up on what they do!

**Comment by rck1** [comment]
Thank you @zellski.  I eagerly await your next release!

**Comment by zellski** [comment]
@rck1 This commit should simplify your situation some: https://github.com/facebookincubator/FBX2glTF/commit/7c0715c4ad945f134143e315c4f77424fd05cc44

I intend to get a release out before day's end.

**Comment by rck1** [comment]
@zellski Awesome!  Thank you for your efforts!

**Comment by rck1** [comment]
Thanks @zellski.  This latest release worked out well for common materials.
