### ISSUE TITLE
Acces denied.

### ISSUE THREAD

**Issue by grebert** [facebookincubator/FBX2glTF#82]
Hi! I have a problem now using FBX2glTF. 
First time I tried to make .fbx to .glb in dos it worked but it told me this:

```
C:\PATH>FBX2glTF-windows-x64.exe \3d_NAME.fbx -b
Warning: node /RootNode/Active Camera uses unsupported transform inheritance type 'eInheritRrSs'.
         (Further warnings of this type squelched.)
Wrote 804613 bytes of binary glTF to ./3d_NAME.glb.
```
and then even I'm Admin, I everytime have access denied

```
C:\PATH>FBX2glTF-windows-x64.exe \3d_NAME.fbx -b
Access denied.
```
I added the softwear autorization in the firewall but it still doesn't work...
Have you encounter this problem? 

Thanks a lot, 
Grebert

**Comment by zellski** [comment]
Hi @grebert,

The warning you got is pretty common, and is **usually** harmless. It's just a feature of FBX that glTF doesn't support. If the model looks okay, ignore it.

As for the 'Access denied.' I'm afraid I have no idea. That looks like Windows just isn't letting you run the binary, for some Windows-specific reason that I can't even begin to guess at. I have long since stopped trying to keep up with how permissions work in Microsoft operating systems. Can anyone else help?

If it's anything like Unix permissions, you just need to figure out how to explicitly give yourself execute-permission on this file. It's also possible there's some kind of virus protection software or whatnot running on your machine that decided that this random download is too dangerous for you to run.

**Comment by grebert** [comment]
Thanks a lot @zellski for your rapid answer, 
I'll try to run the software on another computers to see if it works.
Thanks
