### ISSUE TITLE
VC++ Runtime Library report error when converting a model in Debug mode

### ISSUE THREAD

**Issue by LHC3DArthur** [facebookincubator/FBX2glTF#83]
Build successfully with Visual Studio 2017, but when use Debug->Start new instance，(with fbx file path and options presented in debug params) the Visual studio pop up a message box sayng "HEAP CORRUPTION DETECTED after normal block (#41458) at 0x00002149846C820...". And this message box cannot be closed by push close, retry or ignore button as normal.
I have updated the Visual Studio to 2017 v 15.5.7, but still cannot fix this. And my system is Windows 10.
I got same error while using the debug version .exe file generated by my Visual Studio, but with release version, the error may not appear.

**Comment by zellski** [comment]
@LHC3DArthur -- I will explore this as best as I can; it's possible there's some very basic memory mismanagement somewhere that's being detected properly in debug mode, but for whatever reason is actually harmless when we run it in release mode.

However, I think there is a very strong chance that the problem here is that the Autodesk FBX SDK, which we unavoidably must link against, is actually built against Visual Studio 2015. As far as I'm concerned it's mere luck that building the whole FBX2glTF app with VS2017 works at all, as they erly on different runtime libraries.

Autodesk is working on a updated build of the SDK, I believe -- but until then it's possible debugging just won't work. Unfortunately building with VS2015 is not an option either, since its support for C++11 is too limited.

**Comment by LHC3DArthur** [comment]
Thanks a lot for reply. Hope the SDK's and runtimes will match each other soon.

**Comment by LHC3DArthur** [comment]
Fond the reason.  In AccessorData.h, appendAsBinaryArray() method, while type.write() writing to a std::vector buffer (the 'out' param of the method), it may touch over the end of the buffer, and while next time call the out.resize(), Visual studio report this error(because it will deallocate memory in that function, and found the debug info after the buffer has been changed). May be this is a Visual Studio debug mode only issue and is associated with its memory alloc strategy, but I recommend that modify these lines of code like this to get more safe:

void appendAsBinaryArray(const std::vector<T> &in, std::vector<uint8_t>&out)

{

        const unsigned int stride = type.byteStride();

        const size_t       offset = out.size();

        const size_t       count  = in.size();


        this->count = (unsigned int) count;


		
		// Seems type.write() to a vector is not safe.

		// consider use a temp array then push back to that vector？


		// alloc a bigger memory buffer to prevent writing over the end of it.

		uint8_t * arr = new uint8_t[count * stride * 2];


		for (int ii = 0; ii < count; ii++) {

			type.write(arr + ii * stride, in[ii]);

		}


		for (size_t ii = 0; ii < count * stride; ii++)
		{
			out.push_back(arr[ii]);
		}


	delete[] arr;


        //out->resize(newSize);

        //for (int ii = 0; ii < count; ii ++) {

        //    type.write(&((*out)[offset + ii * stride]), in[ii]);

        //}


}

I have tested this for several models and this error not appeared anymore.
Sorry for my English, and I'm a new to GitHub.

**Comment by LHC3DArthur** [comment]
@zellski

**Comment by LHC3DArthur** [comment]
or... maybe you will consider change a safer way to implement the write() method...

**Comment by zellski** [comment]
Thanks @LHC3DArthur -- I concluded roughly the same thing last night. We must've investigated in parallel.

I have found the underlying issue & fixed it, and will make a release ASAP.
