### ISSUE TITLE
NPM package: When exporting as .gltf output path is incorrect

### ISSUE THREAD

**Issue by robertlong** [facebookincubator/FBX2glTF#91]
When exporting as .gltf using the `fbx2gltf` npm package the output path is incorrect. Files are placed in the `<outputPath>/<fileName>_out` directory but the output path is returned as `<outputPath>/<fileName>.gltf`.

**Comment by zellski** [comment]
This appears to be working now.

**Comment by SBRK** [comment]
@zellski This is still broken for me. It's very counter intuitive :
- If I specify output as `/path/to/file.gltf` file path, I get `/path/to/file_out/file.gltf`, but the function returns the original path (`/path/to/file.gltf`) as `destPath`
- If I specify output as `/path/to/file_out/file.gltf` file path, I get `/path/to/file_out/file_out/file.gltf`
- If I specify output as `/path/to/` I get an error because I don't pass a `.gltf` path

It makes using this tool for scripting file conversions and putting them at a specific location more difficult...

**Comment by zellski** [comment]
Yikes. This is bad indeed. Just to make sure: you are using 0.9.7, right? Or the patch, I guess; 0.9.7-something.

**Comment by SBRK** [comment]
Yes, I tried both the latest (0.9.7-p) and 0.9.6 in case there was a regression between 0.9.6 that supposedly fixed the problem and the newest version, but both failed. I have the same problem with the Ubuntu WSL so I guess it's not specific to Windows

**Comment by zellski** [comment]
I'm in the middle of launching a separate open source project, but I will try to get to this soon. That said, if you are at all comfortable with JavaScript, a pull request would almost certainly get the job done faster.

**Comment by SBRK** [comment]
@zellski I just tried fixing the js and I'm affraid the binary is the problem. I fixed the output path so that it passes the extension in the path, it was not the case. It works fine with glb, but when converting to .gltf, it still produces an `_out` folder.
I now have:
- output `/path/to/file.glb` => produces `/path/to/file/glb`
- output `/path/to/file.gltf` => produces `/path/to/file.gltf_out/file.gltf.gltf`

**Comment by SBRK** [comment]
Ok, my bad. I was still using the previous version of the binary. It works as intended with the latest version, I will push my fix for the js part

**Comment by SBRK** [comment]
Here's the PR https://github.com/facebookincubator/FBX2glTF/pull/233
